from ceefax.fonts.font import Font
from ceefax.fonts.size7extracondensed import size7extracondensedfont

letters = {"|": "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x",
           "-": "xx\n"
                "xx\n"
                "xx\n"
                " x\n"
                "xx\n"
                "xx\n"
                "xx",
           "&": "xxxx\n"
                "xxxx\n"
                "x xx\n"
                "   x\n"
                "x xx\n"
                "xxxx\n"
                "xxxx",
           "'": " x\n"
                " x\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx",
           "(": "xxx\n"
                "' x\n"
                " 'x\n"
                " 'x\n"
                " 'x\n"
                ", x\n"
                "xxx",
           ")": "xxx\n"
                " 'x\n"
                "' x\n"
                "' x\n"
                "' x\n"
                " ,x\n"
                "xxx",
           "!": "xxx\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "xxx\n"
                "  x\n"
                "xxx",
           "?": "xxxxxx\n"
                "'   'x\n"
                ",,x  x\n"
                "xx  ,x\n"
                "xx,,xx\n"
                "xx  xx\n"
                "xxxxxx",
           "/": "xxxxxx\n"
                "xxxx x\n"
                "xxx xx\n"
                "xx xxx\n"
                "x xxxx\n"
                " xxxxx\n"
                "xxxxxx",
           " ": "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx",
           "A": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                "     x\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "B": "xxxxxx\n"
                "    'x\n"
                "  x  x\n"
                "    'x\n"
                "  x  x\n"
                "    ,x\n"
                "xxxxxx",
           "C": "xxxxx\n"
                "'   x\n"
                "  xxx\n"
                "  xxx\n"
                "  xxx\n"
                ",   x\n"
                "xxxxx",
           "D": "xxxxxx\n"
                "    'x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "    ,x\n"
                "xxxxxx",
           "E": "xxxxx\n"
                "    x\n"
                "  xxx\n"
                "   xx\n"
                "  xxx\n"
                "    x\n"
                "xxxxx",
           "F": "xxxxx\n"
                "    x\n"
                "  xxx\n"
                "   xx\n"
                "  xxx\n"
                "  xxx\n"
                "xxxxx",
           "G": "xxxxxx\n"
                "'   'x\n"
                "  xxxx\n"
                "  x''x\n"
                "  x  x\n"
                ",    x\n"
                "xxxxxx",
           "H": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "     x\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "I": "xxx\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "xxx",
           "J": "xxxxx\n"
                "xx  x\n"
                "xx  x\n"
                "xx  x\n"
                "xx  x\n"
                "   ,x\n"
                "xxxxx",
           "K": "xxxxxx\n"
                "  x  x\n"
                "  x ,x\n"
                "   'xx\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "L": "xxxxx\n"
                "  xxx\n"
                "  xxx\n"
                "  xxx\n"
                "  xxx\n"
                "    x\n"
                "xxxxx",
           "M": "xxxxxx\n"
                " 'x' x\n"
                "     x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "N": "xxxxxx\n"
                "    'x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "O": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "P": "xxxxxx\n"
                "    'x\n"
                "  x  x\n"
                "    ,x\n"
                "  xxxx\n"
                "  xxxx\n"
                "xxxxxx",
           "Q": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                ",    x\n"
                "xxxxxx",
           "R": "xxxxxx\n"
                "    'x\n"
                "  x  x\n"
                "    ,x\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "S": "xxxxx\n"
                "'   x\n"
                "  xxx\n"
                ",  'x\n"
                "xx  x\n"
                "   ,x\n"
                "xxxxx",
           "T": "xxxxx\n"
                "    x\n"
                "x  xx\n"
                "x  xx\n"
                "x  xx\n"
                "x  xx\n"
                "xxxxx",
           "U": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "V": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "   ,xx\n"
                "xxxxxx",
           "W": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                "     x\n"
                " ,x, x\n"
                "xxxxxx",
           "X": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "x   xx\n"
                "  x  x\n"
                "  x  x\n"
                "xxxxxx",
           "Y": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                ",    x\n"
                "xxx  x\n"
                "x   ,x\n"
                "xxxxxx",
           "Z": "xxxxx\n"
                "    x\n"
                "xx' x\n"
                "x   x\n"
                " ,xxx\n"
                "    x\n"
                "xxxxx",
           "1": "xxx\n"
                "' x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "xxx",
           "2": "xxxxxx\n"
                "'   'x\n"
                ",,x  x\n"
                "x'  ,x\n"
                "  ,xxx\n"
                "     x\n"
                "xxxxxx",
           "3": "xxxxxx\n"
                "'   'x\n"
                ",,x  x\n"
                "xx  'x\n"
                "''x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "4": "xxxxxx\n"
                "  x  x\n"
                "  x  x\n"
                "     x\n"
                "xxx  x\n"
                "xxx  x\n"
                "xxxxxx",
           "5": "xxxxxx\n"
                "     x\n"
                "  xxxx\n"
                "    'x\n"
                "xxx  x\n"
                "    xx\n"
                "xxxxxx",
           "6": "xxxxxx\n"
                "'   'x\n"
                "  x,,x\n"
                "    'x\n"
                "  x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "7": "xxxxxx\n"
                "     x\n"
                "xxx  x\n"
                "xxx  x\n"
                "xxx  x\n"
                "xxx  x\n"
                "xxxxxx",
           "8": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                "x   xx\n"
                "  x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "9": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                ",    x\n"
                "''x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "0": "xxxxxx\n"
                "'   'x\n"
                "  x  x\n"
                "  x  x\n"
                "  x  x\n"
                ",   ,x\n"
                "xxxxxx",
           ".": "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                " x\n"
                "xx",
           "*": "xxxxx xxxxxx\n"
                "x,'xx,xx',xx\n"
                "xxx'   'xxxx\n"
                ",,x     x,,x\n"
                "xxx,   ,xxxx\n"
                "x',xx'xx,'xx\n"
                "xxxxx xxxxxx",
           # cloud
           "@": "xxxxxxxxxxxxx\n"
                "xxxx'''xxxxxx\n"
                "x'',xxx,'xxxx\n"
                " xx,xxx',,,'x\n"
                ",'''''''''',x\n"
                "xxxxxxxxxxxxx\n"
                "xxxxxxxxxxxxx",
           # rain
           "{": "xxx',,,'xxxxx\n"
                "',,'xxxx ''xx\n"
                " xxxxxx,xxx x\n"
                "x,,,,,,,,,,xx\n"
                "xx','xxxx'xxx\n"
                "x,''',x',x,'x\n"
                "xxxxxxx,''',x",
           # moon
           "}": "xxx'' ,,x\n"
                "x'   ,xxx\n"
                "'   xxxxx\n"
                "    xxxxx\n"
                ",   xxxxx\n"
                "x,   'xxx\n"
                "xxx,, ''x",
           # cloud sun
           "~": "xxxxxxxxxxxxxxxx\n"
                "xxx',,,'xx xx'xx\n"
                "',,'xxxx ''x,xxx\n"
                " xxxxxx,xxx x,,x\n"
                "x,,,,,,,,,,x'xxx\n"
                "xxxxxxxxxx xx,xx\n"
                "xxxxxxxxxxxxxxxx",
           # storm
           "^": "xxx',,,'xxxxx\n"
                "',,'xxxx'xxxx\n"
                " xxxxxx, ''xx\n"
                "x,,x'   ,,,'x\n"
                "xxx,  'xxxx x\n"
                "xxxxx,  'x',x\n"
                "xxxx' ,x,x,xx",
           # snow
           "%": "xxx',,,'xxxxx\n"
                "',,'xxxx ''xx\n"
                " xxxxxx,xxx x\n"
                "x,,,,,,,,,,xx\n"
                "xxxxxx,',xxxx\n"
                "x,',xx,x,xxxx\n"
                "x,x,xxxxxxxxx"}

size7condensedfont = Font(
    letters, squashed=size7extracondensedfont)
