from random import choice
from ceefax.fonts.font import Font
from ceefax.fonts.size7condensed import size7condensedfont

letters = {"'": " x\n"
                " x\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx\n"
                "xx",
           "&": "xxxx\n"
                "xxxx\n"
                "x xx\n"
                "   x\n"
                "x xx\n"
                "xxxx\n"
                "xxxx",
           "#": "xxxxxx\n"
                "x x xx\n"
                "     x\n"
                "x x xx\n"
                "     x\n"
                "x x xx\n"
                "xxxxxx",
           "|": "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x\n"
                "x",
           "-": "xxxx\n"
                "xxxx\n"
                "xxxx\n"
                "   x\n"
                "xxxx\n"
                "xxxx\n"
                "xxxx",
           ".": "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx\n"
                "  x\n"
                "xxx",
           ":": "xxx\n"
                "xxx\n"
                "''x\n"
                ",,x\n"
                "''x\n"
                ",,x\n"
                "xxx",
           "!": "xxx\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "xxx\n"
                "  x\n"
                "xxx",
           "?": "xxxxxxx\n"
                "'    'x\n"
                ",,xx  x\n"
                "xx'  ,x\n"
                "xx,,xxx\n"
                "xx  xxx\n"
                "xxxxxxx",
           "(": "xxxx\n"
                "x  x\n"
                "  xx\n"
                " xxx\n"
                "  xx\n"
                "x  x\n"
                "xxxx",
           ")": "xxxx\n"
                "x  x\n"
                "xx\n"
                "xxx\n"
                "xx\n"
                "x  x\n"
                "xxxx",
           "/": "xxxxxx\n"
                "xxxx x\n"
                "xxx xx\n"
                "xx xxx\n"
                "x xxxx\n"
                " xxxxx\n"
                "xxxxxx",
           " ": "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx\n"
                "xxx",
           u"£": "xxxxxxx\n"
                 "x'   'x\n"
                 "x  x,,x\n"
                 "    xxx\n"
                 "x  xxxx\n"
                 "      x\n"
                 "xxxxxxx",
           u"$": "xxxxxxx\n"
                 "xx  xxx\n"
                 "  ,,,,x\n"
                 "      x\n"
                 "''''  x\n"
                 "xx  xxx\n"
                 "xxxxxxx",
           u"€": "xxxxxxx\n"
                 "x'   'x\n"
                 "'  'xxx\n"
                 "'  'xxx\n"
                 "x  xxxx\n"
                 "x,   ,x\n"
                 "xxxxxxx",
           u"฿": "xxxxxxxxxxxxx\n"
                 "xxxxxx' ' 'xx\n"
                 "xxxxxx  xx  x\n"
                 " , ,'x    ''x\n"
                 " x x x  xx  x\n"
                 " x x x, , ,xx\n"
                 "xxxxxxxxxxxxx",
           u"₺": "xxxxxxx\n"
                 "x  x'xx\n"
                 "'  ,xxx\n"
                 "x  ',xx\n"
                 ",  x''x\n"
                 "x    ,x\n"
                 "xxxxxxx",
           u"¥": "xxxxxxx\n"
                 "  xx  x\n"
                 "  ''  x\n"
                 "x,  ,xx\n"
                 "x,  ,xx\n"
                 "x,  ,xx\n"
                 "xxxxxxx",
           "A": "xxxxxxx\n"
                "x'  'xx\n"
                "  xx  x\n"
                "  ''  x\n"
                "  ,,  x\n"
                "  xx  x\n"
                "xxxxxxx",
           "B": "xxxxxxx\n"
                "     'x\n"
                "  xx  x\n"
                "     xx\n"
                "  xx  x\n"
                "     ,x\n"
                "xxxxxxx",
           "C": "xxxxxxx\n"
                "'    'x\n"
                "  xx,,x\n"
                "  xxxxx\n"
                "  xx''x\n"
                ",    ,x\n"
                "xxxxxxx",
           "D": "xxxxxxx\n"
                "     xx\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                "     xx\n"
                "xxxxxxx",
           "E": "xxxxxxx\n"
                "      x\n"
                "  xxxxx\n"
                "    xxx\n"
                "  xxxxx\n"
                "      x\n"
                "xxxxxxx",
           "F": "xxxxxxx\n"
                "      x\n"
                "  xxxxx\n"
                "    xxx\n"
                "  xxxxx\n"
                "  xxxxx\n"
                "xxxxxxx",
           "G": "xxxxxxx\n"
                "'    'x\n"
                "  xx,,x\n"
                "  x'''x\n"
                "  x,  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "H": "xxxxxxx\n"
                "  xx  x\n"
                "  xx  x\n"
                "      x\n"
                "  xx  x\n"
                "  xx  x\n"
                "xxxxxxx",
           "I": "xxx\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "  x\n"
                "xxx",
           "J": "xxxxxx\n"
                "xxx  x\n"
                "xxx  x\n"
                "xxx  x\n"
                "''x  x\n"
                ",   ,x\n"
                "xxxxxx",
           "K": "xxxxxxx\n"
                "  xx  x\n"
                "  x  xx\n"
                "    xxx\n"
                "  x  xx\n"
                "  xx  x\n"
                "xxxxxxx",
           "L": "xxxxxx\n"
                "  xxxx\n"
                "  xxxx\n"
                "  xxxx\n"
                "  xxxx\n"
                "     x\n"
                "xxxxxx",
           "M": "xxxxxxxxx\n"
                "  xxxx  x\n"
                "   ''   x\n"
                "  ,  ,  x\n"
                "  x,,x  x\n"
                "  xxxx  x\n"
                "xxxxxxxxx",
           "N": "xxxxxxxx\n"
                "   xx  x\n"
                "    x  x\n"
                "  x    x\n"
                "  xx   x\n"
                "  xxx  x\n"
                "xxxxxxxx",
           "O": "xxxxxxx\n"
                "'    'x\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "P": "xxxxxxx\n"
                "     'x\n"
                "  xx  x\n"
                "     ,x\n"
                "  xxxxx\n"
                "  xxxxx\n"
                "xxxxxxx",
           "Q": "xxxxxxx\n"
                "'    'x\n"
                "  xx  x\n"
                "  xx  x\n"
                "  x'',x\n"
                ", ',  x\n"
                "xxxxxxx",
           "R": "xxxxxxx\n"
                "     'x\n"
                "  xx  x\n"
                "     ,x\n"
                "  xx 'x\n"
                "  xx  x\n"
                "xxxxxxx",
           "S": "xxxxxxx\n"
                "'    'x\n"
                "  xxxxx\n"
                ",    'x\n"
                "xxxx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "T": "xxxxxxx\n"
                "      x\n"
                "xx  xxx\n"
                "xx  xxx\n"
                "xx  xxx\n"
                "xx  xxx\n"
                "xxxxxxx",
           "U": "xxxxxxx\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "V": "xxxxxxx\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                "x    xx\n"
                "xx  xxx\n"
                "xxxxxxx",
           "W": "xxxxxxxxx\n"
                "  xxxx  x\n"
                "  xxxx  x\n"
                "  x  x  x\n"
                "        x\n"
                "x  xx  xx\n"
                "xxxxxxxxx",
           "X": "xxxxxxx\n"
                "  xx  x\n"
                "x '' xx\n"
                "xx  xxx\n"
                "x ,, xx\n"
                "  xx  x\n"
                "xxxxxxx",
           "Y": "xxxxxxx\n"
                "  xx  x\n"
                "  xx  x\n"
                "x    xx\n"
                "xx  xxx\n"
                "xx  xxx\n"
                "xxxxxxx",
           "Z": "xxxxxxx\n"
                "      x\n"
                "xxx  xx\n"
                "xx  xxx\n"
                "x  xxxx\n"
                "      x\n"
                "xxxxxxx",
           "1": "xxxx\n"
                "'  x\n"
                ",  x\n"
                "x  x\n"
                "x  x\n"
                "x  x\n"
                "xxxx",
           "2": "xxxxxxx\n"
                "'    'x\n"
                ",,xx  x\n"
                "x'   ,x\n"
                "' ,xxxx\n"
                "      x\n"
                "xxxxxxx",
           "3": "xxxxxxx\n"
                "'    'x\n"
                ",,xx  x\n"
                "xx   ,x\n"
                "''xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "4": "xxxxxxx\n"
                "  xxxxx\n"
                "  xxxxx\n"
                "  x  xx\n"
                "      x\n"
                "xxx  xx\n"
                "xxxxxxx",
           "5": "xxxxxxx\n"
                "      x\n"
                "  '''xx\n"
                ",,,,  x\n"
                "''xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "6": "xxxxxxx\n"
                "'    'x\n"
                "  xx,,x\n"
                "     'x\n"
                "  xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "7": "xxxxxxx\n"
                "      x\n"
                "xxxx  x\n"
                "xx'  xx\n"
                "xx  xxx\n"
                "xx  xxx\n"
                "xxxxxxx",
           "8": "xxxxxxx\n"
                "'    'x\n"
                "  xx  x\n"
                "'    'x\n"
                "  xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "9": "xxxxxxx\n"
                "'    'x\n"
                "  xx  x\n"
                ",     x\n"
                "''xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "0": "xxxxxxx\n"
                "'    'x\n"
                "  xx  x\n"
                "  xx  x\n"
                "  xx  x\n"
                ",    ,x\n"
                "xxxxxxx",
           "*": "xxxxxxx xxxxxxxx\n"
                "xxx,'xx,xx',xxxx\n"
                "xxxxx'   'xxxxxx\n"
                "xx,,x     x,,xxx\n"
                "xxxxx,   ,xxxxxx\n"
                "xxx',xx'xx,'xxxx\n"
                "xxxxxxx xxxxxxxx",
           # cloud
           "@": "xxxxxxxxxxxxxxxx\n"
                "xxxx',,,,,'xxxxx\n"
                "x'' xxxxxxx xxxx\n"
                " xxx,xxxx'',,,'x\n"
                " 'xxxxxxxxxxxx x\n"
                "x,,,,,,,,,,,,,xx\n"
                "xxxxxxxxxxxxxxxx",
           # cloud
           ">": "----------------\n"
                "----,''''',-----\n"
                "-,,x-------x----\n"
                "x---'----,,''',-\n"
                "x,------------x-\n"
                "-'''''''''''''--\n"
                "----------------",
           # cloud sun rain
           "<": "xxxxxxxxxxxxxxxx\n"
                "xxx',,,'xx xx'xx\n"
                "',,'xxxx ''x,xxx\n"
                " xxxxxx,xxx x,,x\n"
                "x,x'x,,,,,,x'xxx\n"
                "x',x,'xxxx xx,xx\n"
                "xx,,,xxxxxxxxxxx",
           # light rain
           "[": "xxxxxxxxxxxxxxxx\n"
                "xxxxx',,,'xxxxxx\n"
                "xx',,'xxxx ''xxx\n"
                "xx xxxx'x,xxx xx\n"
                "xxx,x',,'x,,,xxx\n"
                "xxxx xxx xxxxxxx\n"
                "xxxxx,,,xxxxxxxx",
           # rain
           "{": "xxxxx',,,'xxxxxx\n"
                "xx',,'xxxx ''xxx\n"
                "xx xxxxxx,xxx xx\n"
                "xxx,,,,,,,,,,xxx\n"
                "xxxx','xxxx'xxxx\n"
                "xxx,''',x',x,'xx\n"
                "xxxxxxxxx,''',xx",
           # moon
           "}": "xxxxxx'' ,,xxxxx\n"
                "xxxx'   ,xxxxxxx\n"
                "xxx'   xxxxxxxxx\n"
                "xxx    xxxxxxxxx\n"
                "xxx,   xxxxxxxxx\n"
                "xxxx,   'xxxxxxx\n"
                "xxxxxx,, ''xxxxx",
           # cloud sun
           "~": "xxxxxxxxxxxxxxxx\n"
                "xxx',,,'xx xx'xx\n"
                "',,'xxxx ''x,xxx\n"
                " xxxxxx,xxx x,,x\n"
                "x,,,,,,,,,,x'xxx\n"
                "xxxxxxxxxx xx,xx\n"
                "xxxxxxxxxxxxxxxx",
           # heavy rain
           "]": "xxxx'',,,'xxxxxx\n"
                "',,,'xxxxx ''''x\n"
                " xxxxxxxx,xxxxxx\n"
                ",''''''''''xx'x,\n"
                "xx'xxxxx'xx',x,'\n"
                "',x,'x',x,'x,,,x\n"
                "x,,,xxx,,,xxxxxx",
           # storm
           "^": "xxxxx',,,'xxxxxx\n"
                "xx',,'xxxx ''xxx\n"
                "xx xxxxxx,xxx xx\n"
                "xxx,,x'   ,x,xxx\n"
                "xxxxx,  'xxxxxxx\n"
                "xxxxxxx,  xxxxxx\n"
                "xxxxxx' ,xxxxxxx",
           # snow
           "%": "xxxxx',,,'xxxxxx\n"
                "xx',,'xxxx ''xxx\n"
                "xx xxxxxx,xxx xx\n"
                "xxx,,,,,,,,,,xxx\n"
                "xxxxxxxx,',xxxxx\n"
                "xxx,',xx,x,xxxxx\n"
                "xxx,x,xxxxxxxxxx",
           # unknown
           "`": "\n".join(["".join([choice(["x", ",", "'"])
                                    for i in range(16)])
                           for j in range(7)])}

size7font = Font(letters, squashed=size7condensedfont)
